version: '2'
services:

  webapp_redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  webapp_mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  webapp_itself:
    container_name: webapp
    image: webapp:latest
    ports:
      - "63380:63380"
    links:
      - webapp_redis
      - webapp_mongo
    environment:
      - APP_REDIS_URI=redis://webapp_redis:6379
      - APP_MONGO_URI=mongodb://webapp_mongo:27017/app
      - APP_SERVER_PORT=63380


# monitoring

  influxdbData:
    image: busybox
    volumes:
      - ./data/influxdb:/data

  influxdb:
    image: tutum/influxdb:0.13
    restart: always
    environment:
      - PRE_CREATE_DB=cadvisor
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    volumes_from:
      - "influxdbData"

  cadvisor:
    image: google/cadvisor:v0.24.0
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:latest
    restart: always
    links:
      - influxdb:influxsrv
    ports:
      - "3000:3000"
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
      - INFLUXDB_HOST=influxsrv
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root

